### PR TITLE
:postbox: Added server side postcode validation

### LINKED ISSUE #107: Invalid postcode breaks app
Example: https://connecting-to-services-hack.herokuapp.com/results?location=wf157

Should fail more gracefully for an invalid post code?

### PR DESCRIPTION
**Pull request by neilbmclaughlin**
think this is good enough for us. We can add client side validation in the next iteration if it is revealed as problem in the user research.

Fixes #107

### CODE REVIEW

**Comment by neilbmclaughlin** [comment]
Checked with Joe - he's OK with this for the User Zoom session.

**Comment by st3v3nhunt** [comment]
A couple of things:

* The build failed on a lint issue https://travis-ci.org/nhsuk/connecting-to-services-hack-day/builds/151270657#L691
* Entering an invalid postcode shows an empty set of braces after the message e.g.

image

**Comment by st3v3nhunt** [comment]
The lint issue is fixed by https://github.com/nhsuk/connecting-to-services-hack-day/pull/137/commits/90dcda1ef77a65f47d035ee7f3a2bcecb5f4e2dc
If you wanted to merge that and have this branch rebased against it I think that will sort it out.

**Comment by st3v3nhunt** [comment]
Closing in order to reopen to trigger a new build...

**Comment by neilbmclaughlin** [comment]
Ah, OK.

Regarding the blank parentheses - it is a dev/non-dev environment issue. I get an informative error message. Will take a look.

**Comment by st3v3nhunt** [comment]
image

**Comment by neilbmclaughlin** [comment]
Just checked on deployment and all looks good now.

**Pull request merged**
